In [2]:
import pandas as pd
games = pd.read_csv('nfl-big-data-bowl-2024/games.csv')
players = pd.read_csv('nfl-big-data-bowl-2024/players.csv')
plays = pd.read_csv('nfl-big-data-bowl-2024/plays.csv')
tackles = pd.read_csv('nfl-big-data-bowl-2024/tackles.csv')
tw_one = pd.read_csv('nfl-big-data-bowl-2024/tracking_week_1.csv')

In [3]:
games

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr,homeFinalScore,visitorFinalScore
0,2022090800,2022,1,09/08/2022,20:20:00,LA,BUF,10,31
1,2022091100,2022,1,09/11/2022,13:00:00,ATL,NO,26,27
2,2022091101,2022,1,09/11/2022,13:00:00,CAR,CLE,24,26
3,2022091102,2022,1,09/11/2022,13:00:00,CHI,SF,19,10
4,2022091103,2022,1,09/11/2022,13:00:00,CIN,PIT,20,23
...,...,...,...,...,...,...,...,...,...
131,2022110607,2022,9,11/06/2022,13:00:00,WAS,MIN,17,20
132,2022110608,2022,9,11/06/2022,16:05:00,ARI,SEA,21,31
133,2022110609,2022,9,11/06/2022,16:25:00,TB,LA,16,13
134,2022110610,2022,9,11/06/2022,20:20:00,KC,TEN,20,17
135,2022110700,2022,9,11/07/2022,20:15:00,NO,BAL,13,27

In [4]:
players

,nflId,height,weight,birthDate,collegeName,position,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
2,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
3,30842,6-6,267,1984-05-19,UCLA,TE,Marcedes Lewis
4,33084,6-4,217,1985-05-17,Boston College,QB,Matt Ryan
...,...,...,...,...,...,...,...
1678,55200,6-6,266,NaN,Indiana,DT,Ryder Anderson
1679,55212,6-0,230,NaN,Iowa State,ILB,Jake Hummel
1680,55239,6-2,300,NaN,Pennsylvania,DT,Prince Emili
1681,55240,6-1,185,NaN,Buffalo,CB,Ja'Marcus Ingram
1682,55241,6-2,280,NaN,Coastal Carolina,DT,C.J. Brewer

In [5]:
plays

,gameId,playId,ballCarrierId,ballCarrierDisplayName,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,...,preSnapHomeTeamWinProbability,preSnapVisitorTeamWinProbability,homeTeamWinProbabilityAdded,visitorTeamWinProbilityAdded,expectedPoints,expectedPointsAdded,foulName1,foulName2,foulNFLId1,foulNFLId2
0,2022100908,3537,48723,Parker Hesse,(7:52) (Shotgun) M.Mariota pass short middle t...,4,1,10,ATL,TB,...,0.976785,0.023215,-0.006110,0.006110,2.360609,0.981955,NaN,NaN,NaN,NaN
1,2022091103,3126,52457,Chase Claypool,(7:38) (Shotgun) C.Claypool right end to PIT 3...,4,1,10,PIT,CIN,...,0.160485,0.839515,-0.010865,0.010865,1.733344,-0.263424,NaN,NaN,NaN,NaN
2,2022091111,1148,42547,Darren Waller,(8:57) D.Carr pass short middle to D.Waller to...,2,2,5,LV,LAC,...,0.756661,0.243339,-0.037409,0.037409,1.312855,1.133666,NaN,NaN,NaN,NaN
3,2022100212,2007,46461,Mike Boone,(13:12) M.Boone left tackle to DEN 44 for 7 ya...,3,2,10,DEN,LV,...,0.620552,0.379448,-0.002451,0.002451,1.641006,-0.043580,NaN,NaN,NaN,NaN
4,2022091900,1372,47857,Devin Singletary,(8:33) D.Singletary right guard to TEN 32 for ...,2,1,10,BUF,TEN,...,0.836290,0.163710,0.001053,-0.001053,3.686428,-0.167903,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481,2022100204,123,43293,Ezekiel Elliott,(13:31) E.Elliott right tackle to WAS 38 for 1...,1,1,10,DAL,WAS,...,0.638600,0.361400,-0.011542,0.011542,3.642571,-0.504018,NaN,NaN,NaN,NaN
12482,2022091200,3467,46189,Will Dissly,(6:08) G.Smith pass short right to W.Dissly to...,4,1,10,SEA,DEN,...,0.615241,0.384759,-0.025458,0.025458,1.434580,-0.444642,NaN,NaN,NaN,NaN
12483,2022101605,3371,44860,Joe Mixon,(9:35) (Shotgun) J.Mixon left end to CIN 47 fo...,4,1,10,CIN,NO,...,0.667054,0.332946,-0.005164,0.005164,2.115356,0.203819,NaN,NaN,NaN,NaN
12484,2022100207,2777,52449,Jonathan Taylor,(2:02) (Shotgun) J.Taylor up the middle to TEN...,3,1,10,IND,TEN,...,0.410611,0.589389,-0.046648,0.046648,3.946232,-0.976039,NaN,NaN,NaN,NaN
12485,2022102308,905,54572,Dameon Pierce,(12:51) C.Heck reported in as eligible. D.Pie...,2,3,1,HOU,LV,...,0.726639,0.273361,-0.015028,0.015028,4.685974,0.251580,NaN,NaN,NaN,NaN

In [13]:
tackles

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle
0,2022090800,101,42816,1,0,0,0
1,2022090800,393,46232,1,0,0,0
2,2022090800,486,40166,1,0,0,0
3,2022090800,646,47939,1,0,0,0
4,2022090800,818,40107,1,0,0,0
...,...,...,...,...,...,...,...
17421,2022091113,2494,43533,0,0,0,1
17422,2022092502,3510,42406,0,0,0,1
17423,2022091113,3642,43478,0,0,0,1
17424,2022091901,3578,42431,0,0,0,1
17425,2022091901,3845,46199,0,0,0,1

In [ ]:
tackles.columns

In [7]:
tw_one

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
0,2022090800,56,35472.0,Rodger Saffold,1,2022-09-08 20:24:05.200000,76.0,BUF,left,88.370000,27.27,1.62,1.15,0.16,231.74,147.90,NaN
1,2022090800,56,35472.0,Rodger Saffold,2,2022-09-08 20:24:05.299999,76.0,BUF,left,88.470000,27.13,1.67,0.61,0.17,230.98,148.53,pass_arrived
2,2022090800,56,35472.0,Rodger Saffold,3,2022-09-08 20:24:05.400000,76.0,BUF,left,88.560000,27.01,1.57,0.49,0.15,230.98,147.05,NaN
3,2022090800,56,35472.0,Rodger Saffold,4,2022-09-08 20:24:05.500000,76.0,BUF,left,88.640000,26.90,1.44,0.89,0.14,232.38,145.42,NaN
4,2022090800,56,35472.0,Rodger Saffold,5,2022-09-08 20:24:05.599999,76.0,BUF,left,88.720000,26.80,1.29,1.24,0.13,233.36,141.95,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407434,2022091200,3826,NaN,football,49,2022-09-12 23:05:57.799999,NaN,football,left,56.220001,9.89,2.56,1.25,0.25,NaN,NaN,tackle
1407435,2022091200,3826,NaN,football,50,2022-09-12 23:05:57.900000,NaN,football,left,56.060001,10.08,2.50,1.14,0.24,NaN,NaN,NaN
1407436,2022091200,3826,NaN,football,51,2022-09-12 23:05:58.000000,NaN,football,left,55.889999,10.27,2.38,1.70,0.25,NaN,NaN,NaN
1407437,2022091200,3826,NaN,football,52,2022-09-12 23:05:58.099999,NaN,football,left,55.730000,10.44,2.07,2.83,0.24,NaN,NaN,NaN
1407438,2022091200,3826,NaN,football,53,2022-09-12 23:05:58.200000,NaN,football,left,55.570000,10.57,1.86,3.00,0.20,NaN,NaN,NaN

In [8]:
game_id_to_filter = 2022090800
filtered_plays = plays[plays['gameId'] == game_id_to_filter]

In [9]:
filtered_plays

,gameId,playId,ballCarrierId,ballCarrierDisplayName,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,...,preSnapHomeTeamWinProbability,preSnapVisitorTeamWinProbability,homeTeamWinProbabilityAdded,visitorTeamWinProbilityAdded,expectedPoints,expectedPointsAdded,foulName1,foulName2,foulNFLId1,foulNFLId2
209,2022090800,2184,42489,Stefon Diggs,(9:24) (Shotgun) J.Allen pass short left to S....,3,1,10,BUF,LA,...,0.324996,0.675004,-0.013726,0.013726,4.730500,0.406682,NaN,NaN,NaN,NaN
262,2022090800,2307,44881,Cooper Kupp,(7:28) (Shotgun) M.Stafford pass deep left to ...,3,2,10,LA,BUF,...,0.230606,0.769394,0.043359,-0.043359,0.805026,2.080663,NaN,NaN,NaN,NaN
578,2022090800,3304,52494,Zack Moss,(5:27) Z.Moss left tackle to LA 16 for 4 yards...,4,2,6,BUF,LA,...,0.001397,0.998603,0.001232,-0.001232,4.320043,-4.856559,NaN,NaN,NaN,NaN
1131,2022090800,2648,46076,Josh Allen,(:33) (Shotgun) J.Allen up the middle to BUF 4...,3,2,10,BUF,LA,...,0.134761,0.865239,0.015617,-0.015617,2.036072,-0.828860,NaN,NaN,NaN,NaN
1363,2022090800,236,52536,Gabe Davis,(10:03) J.Allen pass short right to G.Davis fo...,1,3,1,BUF,LA,...,0.341447,0.658553,-0.063681,0.063681,4.081674,2.918326,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11576,2022090800,393,47853,Darrell Henderson,(7:45) (Shotgun) D.Henderson right guard to LA...,1,1,10,LA,BUF,...,0.314065,0.685935,-0.015263,0.015263,2.458136,-0.386335,NaN,NaN,NaN,NaN
11580,2022090800,3431,53678,Ben Skowronek,"(3:41) (No Huddle, Shotgun) M.Stafford pass sh...",4,2,4,LA,BUF,...,0.002557,0.997443,-0.000063,0.000063,1.420936,0.693287,NaN,NaN,NaN,NaN
11953,2022090800,646,47879,Dawson Knox,(1:53) J.Allen pass short left to D.Knox to LA...,1,1,10,BUF,LA,...,0.204260,0.795740,-0.029484,0.029484,2.706385,1.352469,Horse Collar Tackle,NaN,47939.0,NaN
12048,2022090800,1286,44881,Cooper Kupp,(6:49) M.Stafford pass short left to C.Kupp pu...,2,1,10,LA,BUF,...,0.235913,0.764087,0.007502,-0.007502,3.667560,0.273790,NaN,NaN,NaN,NaN
12206,2022090800,896,54528,James Cook,(13:36) (Shotgun) J.Cook right tackle to BUF 3...,2,2,8,BUF,LA,...,0.225668,0.774332,0.094656,-0.094656,1.077905,-4.717964,NaN,NaN,NaN,NaN

In [14]:
plays = plays.merge(tackles[['gameId', 'playId', 'nflId', 'tackle', 'assist', 'forcedFumble', 'pff_missedTackle']],
                                      on=['gameId', 'playId'], how='left')

In [15]:
plays

,gameId,playId,ballCarrierId,ballCarrierDisplayName,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,...,expectedPointsAdded,foulName1,foulName2,foulNFLId1,foulNFLId2,nflId,tackle,assist,forcedFumble,pff_missedTackle
0,2022100908,3537,48723,Parker Hesse,(7:52) (Shotgun) M.Mariota pass short middle t...,4,1,10,ATL,TB,...,0.981955,NaN,NaN,NaN,NaN,43306.0,1.0,0.0,0.0,0.0
1,2022091103,3126,52457,Chase Claypool,(7:38) (Shotgun) C.Claypool right end to PIT 3...,4,1,10,PIT,CIN,...,-0.263424,NaN,NaN,NaN,NaN,44872.0,1.0,0.0,0.0,0.0
2,2022091103,3126,52457,Chase Claypool,(7:38) (Shotgun) C.Claypool right end to PIT 3...,4,1,10,PIT,CIN,...,-0.263424,NaN,NaN,NaN,NaN,47855.0,0.0,0.0,0.0,1.0
3,2022091111,1148,42547,Darren Waller,(8:57) D.Carr pass short middle to D.Waller to...,2,2,5,LV,LAC,...,1.133666,NaN,NaN,NaN,NaN,47843.0,1.0,0.0,0.0,0.0
4,2022100212,2007,46461,Mike Boone,(13:12) M.Boone left tackle to DEN 44 for 7 ya...,3,2,10,DEN,LV,...,-0.043580,NaN,NaN,NaN,NaN,53509.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17882,2022101605,3371,44860,Joe Mixon,(9:35) (Shotgun) J.Mixon left end to CIN 47 fo...,4,1,10,CIN,NO,...,0.203819,NaN,NaN,NaN,NaN,41257.0,0.0,0.0,0.0,1.0
17883,2022100207,2777,52449,Jonathan Taylor,(2:02) (Shotgun) J.Taylor up the middle to TEN...,3,1,10,IND,TEN,...,-0.976039,NaN,NaN,NaN,NaN,47971.0,1.0,0.0,0.0,0.0
17884,2022100207,2777,52449,Jonathan Taylor,(2:02) (Shotgun) J.Taylor up the middle to TEN...,3,1,10,IND,TEN,...,-0.976039,NaN,NaN,NaN,NaN,43388.0,0.0,1.0,0.0,0.0
17885,2022102308,905,54572,Dameon Pierce,(12:51) C.Heck reported in as eligible. D.Pie...,2,3,1,HOU,LV,...,0.251580,NaN,NaN,NaN,NaN,42391.0,0.0,1.0,0.0,0.0
17886,2022102308,905,54572,Dameon Pierce,(12:51) C.Heck reported in as eligible. D.Pie...,2,3,1,HOU,LV,...,0.251580,NaN,NaN,NaN,NaN,53509.0,0.0,1.0,0.0,0.0